[package]
name = "semantic-search"
version = "0.1.0"
edition = "2021"
include = ["/src", "README.md"]
description = "🔎 Semantic search library."
license = "gpl-3.0-or-later"
repository = "https://github.com/PRO-2684/Semantic-Search"
keywords = ["search", "semantic", "library"]
categories = ["command-line-utilities", "development-tools"]
