[workspace]
resolver = "2"
members = ["semantic-search", "semantic-search-cli"]

[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true  # Enable link-time optimization.
codegen-units = 1  # Set the number of codegen units to 1.
