[package]
name = "semantic-search-cli"
version = "0.1.0"
edition = "2021"
include = ["/src", "README.md"]
description = "🔎 Semantic search cli."
license = "gpl-3.0-or-later"
repository = "https://github.com/PRO-2684/Semantic-Search"
keywords = ["search", "semantic", "cli"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1.0.96"
argh = "0.1.13"
base16ct = { version = "0.2.0", features = ["alloc"] }
env_logger = "0.11.6"
futures-core = "0.3.31"
futures-util = "0.3.31"
log = "0.4.26"
semantic-search = { path = "../semantic-search", version = "0.1.0" }
serde = { version = "1.0.218", features = ["derive"] }
sha2 = "0.10.8"
sqlx = { version = "0.8.3", features = ["runtime-tokio", "sqlite"] }
teloxide = { version = "0.13.0", features = ["macros", "throttle"] }
tokio = { version = "1.43.0", features = ["rt", "macros"] }
toml = "0.8.20"

[[bin]]
name = "sense"
path = "src/main.rs"
